

- name: Install Terraform Binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: /usr/bin/
    remote_src: yes

- name: create Terraform workdir
  file:
    path: "{{ terraform_workdir }}"
    state: directory
    mode: '0755'

- name: Install Terraform Binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: /usr/bin/
    remote_src: yes



- name: Create Terraform vars file
  template:
    src: cluster.tf.j2
    dest: "{{ terraform_workdir }}/cluster.tf"

- name: Create provider.tf file
  template:
    src: provider.tf.j2
    dest: "{{ terraform_workdir }}/provider.tf"

- name: Create kube.tf file
  template:
    src: kube.tf.j2
    dest: "{{ terraform_workdir }}/kube.tf"

- name: Create variables.tf file
  template:
    src: variables.tf.j2
    dest: "{{ terraform_workdir }}/variables.tf"

- name: Create post instalation script
  template:
    src: post-terraform.sh.j2
    dest: "{{ terraform_workdir }}/post-terraform.sh"
    mode: '0777'
