# - name: Create SSH key for root
#   user:
#     name: root
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: "{{ ssh_public_key_location }}"
# - name: Download CoreOS image
#   command:
#     "curl --compressed -J -L -o {{ coreos_image_location }} https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-{{ coreos_version }}-qemu.qcow2"
#   args:
#     creates: "{{ coreos_image_location }}"

- name: Install Openshift installer
  unarchive:
    src: "{{ ocpinstaller_url }}"
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/openshift-install

- name: Install Openshift client
  unarchive:
    src: "{{ ocpclient_url }}"
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/oc
