#!/usr/bin/env ansible-playbook
---

- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - ../cluster.yml
  tasks:
  - name: Add hetzner server to inventory
    add_host:
      name: "{{ hetzner_hostname }}"
