#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files:
  - ../cluster.yml
  vars:
    ssh_public_key: "{{ lookup('file', '{{ ssh_public_key_location }}.pub') }}"
  gather_facts: false
  roles:
    - bind
    - loadbalancer

    - role: "letsencrypt"
      le_dns_provider: "{{ dns_provider }}"
      le_public_domain: "{{ cluster_name }}.{{ public_domain }}"
      # Only set if you really want a production letsencrypt certificate
      # without le_acme_directory it use the staging env.
      #   https://letsencrypt.org/docs/rate-limits/
      le_acme_directory: "https://acme-v02.api.letsencrypt.org/directory"

      le_letsencrypt_account_email: "{{ letsencrypt_account_email | default(cloudflare_account_email)}}"
      le_cloudflare_account_api_token: "{{ cloudflare_account_api_token }}"
      le_cloudflare_zone: "{{ cloudflare_zone }}"

      le_aws_access_key: "{{ aws_access_key }}"
      le_aws_secret_key: "{{ aws_secret_key }}"
      le_aws_zone: "{{ aws_zone }}"

    - role: ign
      ign_ssh_public_key: "{{ ssh_public_key }}"
      ign_terraform_workdir: "{{ terraform_workdir }}"
