packages_centos:
- "@virtualization-hypervisor"
- "@virtualization-client"
- "@virtualization-platform"
- "@virtualization-tools"
- bind
- "https://www.rdoproject.org/repos/rdo-release.rpm"
- bind-utils
- haproxy
- libguestfs-xfs
- libguestfs-tools
- libvirt
- libvirt-python
- python-lxml
- qemu-kvm
- virt-manager
- virt-install
- libselinux-python
- bash-completion
- iptables-services
- git
- epel-release
- cloud-utils
- tmux
- unzip
- python
- python-devel
- python-pip
packages_fedora:
- python-dnf
- libguestfs-xfs
- libguestfs-tools
- libvirt
- qemu-kvm
- virt-manager
- virt-install
- libguestfs-tools
- libselinux-python
- cloud-utils
- openvswitch
- git
- tmux
packages_debian:
- libguestfs-xfs
- libguestfs-tools
- libvirt-bin
- qemu-kvm
- ubuntu-vm-builder
- virt-manager
- libguestfs-tools
- cloud-utils
- openvswitch-switch
- python-lxml
- virtinst
- bridge-utils
- aptitude
network: ocp4libvirt
